// vant2-ui.js按需导入组件
import Vue from 'vue'
import { Button, Tabbar, TabbarItem, NavBar, Toast, Search, Swipe, SwipeItem, Grid, GridItem, Icon, Sidebar, SidebarItem, Rate, ActionSheet, Dialog, Checkbox, CheckboxGroup, Empty, AddressList, AddressEdit, Tab, Tabs, Skeleton, Card, Tag, Step, Steps } from 'vant'

Vue.use(Tabbar)
Vue.use(Dialog)
Vue.use(TabbarItem)
Vue.use(Button)
Vue.use(NavBar)
Vue.use(Toast)
Vue.use(Search)
Vue.use(Swipe)
Vue.use(SwipeItem)
Vue.use(Grid)
Vue.use(GridItem)
Vue.use(Icon)
Vue.use(Sidebar)
Vue.use(SidebarItem)
Vue.use(Rate)
Vue.use(ActionSheet)
Vue.use(Checkbox)
Vue.use(CheckboxGroup)
Vue.use(Empty)
Vue.use(AddressList)
Vue.use(AddressEdit)
Vue.use(Tab)
Vue.use(Tabs)
Vue.use(Skeleton)
Vue.use(Card)
Vue.use(Tag)
Vue.use(Step)
Vue.use(Steps)
